-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.firebird.search.table : 1.0.0

-- # [ firebird ]
SELECT
    UPPER(RDB$RELATION_FIELDS.RDB$RELATION_NAME) AS "TABLE",
    UPPER(RDB$RELATION_FIELDS.RDB$FIELD_NAME) AS "COLUMN",
    CASE
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 7 THEN 'SMALLINT'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 8 THEN 'INTEGER'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 9 THEN 'QUAD'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 10 THEN 'FLOAT'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 12 THEN 'DATE'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 13 THEN 'TIME'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 14 THEN 'CHAR'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 16 THEN 'BIGINT'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 27 THEN 'DOUBLE PRECISION'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 35 THEN 'TIMESTAMP'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 37 THEN 'VARCHAR'
        WHEN RDB$FIELDS.RDB$FIELD_TYPE = 261 THEN 'BLOB'
        ELSE 'UNKNOWN'
    END AS "COLUMN_TYPE",
    RDB$FIELDS.RDB$FIELD_LENGTH AS "COLUMN_SIZE"
FROM
    RDB$RELATIONS
INNER JOIN
    RDB$RELATION_FIELDS
    ON UPPER(RDB$RELATION_FIELDS.RDB$RELATION_NAME) = UPPER(RDB$RELATIONS.RDB$RELATION_NAME)
INNER JOIN
    RDB$FIELDS
    ON RDB$RELATION_FIELDS.RDB$FIELD_SOURCE = RDB$FIELDS.RDB$FIELD_NAME
WHERE
    RDB$RELATIONS.RDB$SYSTEM_FLAG = 0 -- Only user tables, not system tables
    AND UPPER(RDB$RELATIONS.RDB$RELATION_NAME) LIKE UPPER('%%')
    AND UPPER(RDB$RELATION_FIELDS.RDB$FIELD_NAME) LIKE UPPER('%%')
ORDER BY
    UPPER(RDB$RELATION_FIELDS.RDB$RELATION_NAME),
    RDB$RELATION_FIELDS.RDB$FIELD_POSITION;
