# [ zrfisaac ]

# [ about ]
# - author : Isaac Caires
# . - email : zrfisaac@gmail.com
# . - site : zrfisaac.github.io
# - version : zrfisaac.gitignore.dockerfile : 1.0.0

# [ gitignore ]

# : - dockerfile
*.Identifier

# : - zrfisaac
*.Identifier
*.classified.*
.DS_Store
.git
*.private.*
.temp
.vs
_*
