-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.oracle.sample.user : 1.0.0

-- # [ shell ]

-- # - : C:\app\%USERNAME%\product\21c\dbhomeXE\bin\sqlplus.exe / as sysdba
-- # - : C:\app\%USERNAME%\virtual\product\12.2.0\dbhome_1\bin\sqlplus.exe / as sysdba
-- # - : C:\oraclexe\app\oracle\product\10.2.0\server\BIN\sqlplus.exe sys as sysdba
-- # - : C:\XEClient\bin\sqlplus.exe / as sysdba

-- # [ oracle ]

-- # - : SELECT username FROM dba_users;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

DROP USER O01 CASCADE;
DROP USER O02 CASCADE;
DROP USER O03 CASCADE;
DROP USER O04 CASCADE;
DROP USER O05 CASCADE;

CREATE USER "O01" IDENTIFIED BY "1234" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "DEFAULT" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "O01";
GRANT "CONNECT" TO "O01";
GRANT DBA TO "O01";
GRANT "RESOURCE" TO "O01";
GRANT CREATE SESSION,CREATE TABLE,CREATE VIEW TO O01;
GRANT SELECT ON SYS.USER$ TO O01;
GRANT SELECT ON SYS.OBJ$ TO O01;

CREATE USER "O02" IDENTIFIED BY "1234" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "DEFAULT" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "O02";
GRANT "CONNECT" TO "O02";
GRANT DBA TO "O02";
GRANT "RESOURCE" TO "O02";
GRANT CREATE SESSION,CREATE TABLE,CREATE VIEW TO O02;
GRANT SELECT ON SYS.USER$ TO O02;
GRANT SELECT ON SYS.OBJ$ TO O02;

CREATE USER "O03" IDENTIFIED BY "1234" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "DEFAULT" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "O03";
GRANT "CONNECT" TO "O03";
GRANT DBA TO "O03";
GRANT "RESOURCE" TO "O03";
GRANT CREATE SESSION,CREATE TABLE,CREATE VIEW TO O03;
GRANT SELECT ON SYS.USER$ TO O03;
GRANT SELECT ON SYS.OBJ$ TO O03;

CREATE USER "O04" IDENTIFIED BY "1234" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "DEFAULT" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "O04";
GRANT "CONNECT" TO "O04";
GRANT DBA TO "O04";
GRANT "RESOURCE" TO "O04";
GRANT CREATE SESSION,CREATE TABLE,CREATE VIEW TO O04;
GRANT SELECT ON SYS.USER$ TO O04;
GRANT SELECT ON SYS.OBJ$ TO O04;

CREATE USER "O05" IDENTIFIED BY "1234" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "DEFAULT" ACCOUNT UNLOCK;
GRANT UNLIMITED TABLESPACE TO "O05";
GRANT "CONNECT" TO "O05";
GRANT DBA TO "O05";
GRANT "RESOURCE" TO "O05";
GRANT CREATE SESSION,CREATE TABLE,CREATE VIEW TO O05;
GRANT SELECT ON SYS.USER$ TO O05;
GRANT SELECT ON SYS.OBJ$ TO O05;
