-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.list.column : 0.0.1

-- # [ mssql ]
SELECT
	 [DATABASE]
	,[TABLE]
	,[COLUMN]
	,[TYPE]
	,[SIZE]
	,[NULL]
	,[DEFAULT]
	,(
		REPLACE(
		REPLACE(
		REPLACE(
		REPLACE(
		REPLACE(
		REPLACE(
			(''
				+ CHAR(13) + 'IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.TABLES WITH(NOLOCK) WHERE TABLE_NAME = ''P_TABLE'')'
				+ CHAR(13) + 'CREATE TABLE [P_TABLE] ([P_COLUMN] [P_TYPE] P_SIZE P_NULL P_DEFAULT)'
				+ CHAR(13) + 'IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.COLUMNS WITH(NOLOCK) WHERE TABLE_NAME = ''P_TABLE'' AND COLUMN_NAME = ''P_COLUMN'')'
				+ CHAR(13) + 'ALTER TABLE [P_TABLE] ADD [P_COLUMN] [P_TYPE] P_SIZE P_NULL P_DEFAULT'
			)
			,'P_TABLE'
			,[TABLE]
		)
			,'P_COLUMN'
			,[COLUMN]
		)
			,'P_TYPE'
			,[TYPE]
		)
			,'P_SIZE'
			,[SIZE]
		)
			,'P_NULL'
			,[NULL]
		)
			,'P_DEFAULT'
			,[DEFAULT]
		)
	)
	AS [SCRIPT]
FROM
	(
		SELECT
			 AL_TABLE.TABLE_CATALOG
			AS [DATABASE]
			,AL_TABLE.TABLE_NAME
			AS [TABLE]
			,AL_COLUMN.COLUMN_NAME
			AS [COLUMN]
			,UPPER(AL_COLUMN.DATA_TYPE)
			AS [TYPE]
			,(CASE
				WHEN UPPER(AL_COLUMN.DATA_TYPE) IN (''
					,'DECIMAL'
					,'NUMERIC'
				)
				THEN '(' + CONVERT(VARCHAR,AL_COLUMN.NUMERIC_PRECISION) + ',' + CONVERT(VARCHAR,AL_COLUMN.NUMERIC_SCALE) + ')'
				WHEN UPPER(AL_COLUMN.DATA_TYPE) IN (''
					,'BINARY'
					,'CHAR'
					,'NCHAR'
					,'NVARCHAR'
					,'VARBINARY'
					,'VARCHAR'
				)
				THEN '(' + REPLACE(CONVERT(VARCHAR,AL_COLUMN.CHARACTER_MAXIMUM_LENGTH),'-1','MAX') + ')'
				ELSE ''
			END)
			AS [SIZE]
			,(CASE UPPER(AL_COLUMN.IS_NULLABLE)
				WHEN 'YES'
				THEN 'NULL'
				ELSE 'NOT NULL'
			END)
			AS [NULL]
			,ISNULL('DEFAULT' + ' ' + AL_COLUMN.COLUMN_DEFAULT,'')
			AS [DEFAULT]
			,AL_COLUMN.ORDINAL_POSITION
			AS [ORDER]
		FROM
			INFORMATION_SCHEMA.TABLES AL_TABLE WITH(NOLOCK)
			INNER JOIN INFORMATION_SCHEMA.COLUMNS AS AL_COLUMN WITH(NOLOCK)
				ON AL_COLUMN.TABLE_NAME = AL_TABLE.TABLE_NAME
		WHERE 0 = 0
			AND AL_TABLE.TABLE_TYPE = N'BASE TABLE'
			AND AL_TABLE.TABLE_CATALOG = DB_NAME()
			AND AL_TABLE.TABLE_SCHEMA = SCHEMA_NAME()
	) AS AL_RESULT
ORDER BY
	 [DATABASE]		ASC
	,[TABLE]		ASC
	,[ORDER]		ASC
