-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires Santana
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.refresh : 26.3.6.1

-- # [ mssql ]
DECLARE
	@CR_CURSOR_CL_VIEW	VARCHAR(255)
DECLARE CR_CURSOR CURSOR FOR SELECT
	CL_VIEW = TABLE_NAME
FROM
	INFORMATION_SCHEMA.TABLES AS AL_VIEW WITH(NOLOCK)
WHERE 0 = 0
	AND AL_VIEW.TABLE_TYPE = 'VIEW'
	AND AL_VIEW.TABLE_NAME NOT IN (''
		,''
	)
ORDER BY
	AL_VIEW.TABLE_NAME
OPEN CR_CURSOR
FETCH NEXT FROM CR_CURSOR INTO @CR_CURSOR_CL_VIEW
WHILE (@@FETCH_STATUS = 0)
BEGIN
	PRINT (@CR_CURSOR_CL_VIEW)
	EXEC ('EXEC SP_REFRESHVIEW [' + @CR_CURSOR_CL_VIEW + ']')
	FETCH NEXT FROM CR_CURSOR INTO @CR_CURSOR_CL_VIEW
END
CLOSE CR_CURSOR
DEALLOCATE CR_CURSOR
