-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires Santana
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.simples : 26.5.29.1

-- # [ mssql ]

-- # : TB_DUMMY - CL_ID
IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.TABLES WITH(NOLOCK) WHERE TABLE_NAME = 'TB_DUMMY')
CREATE TABLE TB_DUMMY (CL_ID IDENTITY(1,1)  NOT NULL )
IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.COLUMNS WITH(NOLOCK) WHERE TABLE_NAME = 'TB_DUMMY' AND COLUMN_NAME = 'CL_ID')
ALTER TABLE [TB_DUMMY] ADD CL_ID INT IDENTITY(1,1)  NOT NULL

-- # : TB_DUMMY - CL_NOME
IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.TABLES WITH(NOLOCK) WHERE TABLE_NAME = 'TB_DUMMY')
CREATE TABLE TB_DUMMY (CL_NOME VARCHAR(40)  NOT NULL )
IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.COLUMNS WITH(NOLOCK) WHERE TABLE_NAME = 'TB_DUMMY' AND COLUMN_NAME = 'CL_NOME')
ALTER TABLE [TB_DUMMY] ADD CL_NOME VARCHAR(40)  NOT NULL

-- # : TB_DUMMY - CL_ALTERACAO
IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.TABLES WITH(NOLOCK) WHERE TABLE_NAME = 'TB_DUMMY')
CREATE TABLE TB_DUMMY (CL_CRIACAO DATETIME  NOT NULL DEFAULT GETDATE() )
IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.COLUMNS WITH(NOLOCK) WHERE TABLE_NAME = 'TB_DUMMY' AND COLUMN_NAME = 'CL_CRIACAO')
ALTER TABLE [TB_DUMMY] ADD CL_CRIACAO DATETIME  NOT NULL DEFAULT GETDATE()
