-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.sp.consulta : 1.0.1

-- # [ mssql ]
IF	EXISTS (
	SELECT TOP 1 NULL
	FROM SYSOBJECTS
	WHERE UPPER(NAME) = N'SP_CONSULTA'
	AND UPPER(TYPE) = N'P'
) DROP PROCEDURE SP_CONSULTA
GO
CREATE PROCEDURE SP_CONSULTA @P_CONSULTA VARCHAR(50)
AS
	SELECT
		 (CASE SYSOBJECTS.XTYPE
			WHEN 'F' THEN 'ESTRANGEIRA'
			WHEN 'U' THEN 'TABELA'
			WHEN 'D' THEN 'PADRAO'
			WHEN 'P' THEN 'PROCEDURE'
			WHEN 'S' THEN 'PROCEDURE'
			WHEN 'UQ' THEN 'INDICE'
			WHEN 'C' THEN 'CONSTANTE'
			WHEN 'PK' THEN 'CHAVE'
			WHEN 'TR' THEN 'TRIGGER'
			WHEN 'FN' THEN 'FUNCAO'
			WHEN 'TF' THEN 'FUNCAO'
			WHEN 'V ' THEN 'VISAO'
			ELSE SYSOBJECTS.XTYPE
		END)
		AS OBJETO
		,CONVERT(VARCHAR(50), SYSOBJECTS.NAME)
		AS NOME
		,CONVERT(VARCHAR(30), SYSCOLUMNS.NAME)
		AS COLUNA
		,CONVERT(VARCHAR(30), SYSCOLUMNS.COLORDER)
		AS ORDEM
		,UPPER(CONVERT(VARCHAR(20), SYSTYPES.NAME))
		AS TIPO
		,SYSCOLUMNS.LENGTH
		AS TAMANHO
		,(CASE
			WHEN SYSCOLUMNS.ISNULLABLE = 1
			THEN 'SIM'
			ELSE 'NAO'
		END)
		AS NULO
		,CONVERT(VARCHAR(10),SYSOBJECTS.CRDATE,103) + ' ' + CONVERT(VARCHAR(5),SYSOBJECTS.CRDATE,114)
		AS CRIACAO
	FROM
		SYSCOLUMNS
		INNER JOIN SYSOBJECTS
			ON SYSCOLUMNS.ID = SYSOBJECTS.ID
		INNER JOIN SYSTYPES
			ON SYSCOLUMNS.XTYPE = SYSTYPES.XTYPE
	WHERE
		(
			DBO.SYSCOLUMNS.NAME LIKE '%' + @P_CONSULTA + '%'
			OR
			DBO.SYSOBJECTS.NAME LIKE '%' + @P_CONSULTA + '%'
		)
		AND SYSCOLUMNS.COLORDER > 0
		AND SYSOBJECTS.CATEGORY NOT IN (2)
		AND SYSOBJECTS.XTYPE NOT IN ('IT')
	ORDER BY
		 OBJETO
		,NOME
		,ORDEM
GO
-- /*
EXEC SP_CONSULTA ''
-- */
