-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.sp.consulta : 1.0.0

-- # [ mssql ]
IF	EXISTS (
	SELECT TOP 1 NULL
	FROM SYSOBJECTS
	WHERE UPPER(NAME) = N'SP_CONSULTA'
	AND UPPER(TYPE) = N'P'
) DROP PROCEDURE SP_CONSULTA
GO
CREATE PROCEDURE SP_CONSULTA @P_CONSULTA VARCHAR(50)
AS
	SELECT
		 (CASE SYSOBJECTS.XTYPE
			WHEN 'F' THEN 'FOREN KEY'
			WHEN 'U' THEN 'TABELA'
			WHEN 'D' THEN 'DEFAULT'
			WHEN 'P' THEN 'PROCEDURE'
			WHEN 'S' THEN 'PROCEDURE'
			WHEN 'UQ' THEN 'INDICE'
			WHEN 'C' THEN 'CONSTRAINTS'
			WHEN 'PK' THEN 'RELACIONAMENTOS'
			WHEN 'TR' THEN 'TRIGGER'
			WHEN 'FN' THEN 'FUNÇÃO'
			WHEN 'TF' THEN 'FUNÇÃO'
			WHEN 'V ' THEN 'VIEWS'
			ELSE SYSOBJECTS.XTYPE
		END)
		AS OBJETO
		,CONVERT(VARCHAR(50), SYSOBJECTS.NAME)
		AS NOME
		,CONVERT(VARCHAR(30), SYSCOLUMNS.NAME)
		AS COLUNA
		,CONVERT(VARCHAR(20), SYSTYPES.NAME)
		AS TIPO
		,SYSCOLUMNS.LENGTH
		AS TAMANHO
		,(CASE
			WHEN SYSCOLUMNS.ISNULLABLE = 1
			THEN 'SIM'
			ELSE 'NAO'
		END)
		AS NULO
		,SYSOBJECTS.CRDATE
		AS CRIACAO
	FROM
		SYSCOLUMNS
		INNER JOIN SYSOBJECTS
			ON SYSCOLUMNS.ID = SYSOBJECTS.ID
		INNER JOIN SYSTYPES
			ON SYSCOLUMNS.XTYPE = SYSTYPES.XTYPE
	WHERE
		(
			DBO.SYSCOLUMNS.NAME LIKE '%' + @P_CONSULTA + '%'
			OR
			DBO.SYSOBJECTS.NAME LIKE '%' + @P_CONSULTA + '%'
		)
		AND SYSOBJECTS.XTYPE NOT IN ('IT')
	ORDER BY
		 OBJETO
		,NOME
		,COLUNA
GO
-- /*
EXEC SP_CONSULTA ''
-- */
