-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.table : 1.0.1

-- # [ mssql ]
IF EXISTS (
	SELECT TOP 1 NULL
	FROM INFORMATION_SCHEMA.TABLES
	WHERE INFORMATION_SCHEMA.TABLES.TABLE_TYPE = 'BASE TABLE'
	AND INFORMATION_SCHEMA.TABLES.TABLE_NAME = 'TB_DUMMY'
)
DROP TABLE TB_DUMMY;
IF NOT EXISTS (
	SELECT TOP 1 NULL
	FROM INFORMATION_SCHEMA.TABLES
	WHERE INFORMATION_SCHEMA.TABLES.TABLE_TYPE = 'BASE TABLE'
	AND INFORMATION_SCHEMA.TABLES.TABLE_NAME = 'TB_DUMMY'
)
BEGIN
	CREATE TABLE TB_DUMMY (
		-- # : - column
		 CL_ID			INT	IDENTITY(1, 1)	NOT NULL
		,CL_DUMMY		INT						NULL
		,CL_NAME		VARCHAR		( 400)	NOT NULL
		,CL_VALUE		DECIMAL		(22,2)		NULL
		,CL_PASSWORD	BINARY		(  16)		NULL
		,CL_CHECK		VARCHAR		(   1)	NOT NULL
		,CL_DATE		DATETIME				NULL
			CONSTRAINT DF_TB_DUMMY_CL_CHECK
				DEFAULT('N')
			,CONSTRAINT CT_TB_DUMMY_CL_CHECK
				CHECK(CL_CHECK  IN ('Y','N'))

		-- # : - primary
		,CONSTRAINT PK_TB_DUMMY_CL_ID
		PRIMARY KEY (CL_ID)

		-- # : - foreign
		,CONSTRAINT FK_TB_DUMMY_CL_DUMMY
			FOREIGN KEY (CL_DUMMY)
			REFERENCES TB_DUMMY(CL_ID)
	)
END
INSERT INTO TB_DUMMY
(
     CL_NAME
    ,CL_VALUE
    ,CL_PASSWORD
    ,CL_CHECK
	,CL_DATE
    ,CL_DUMMY
)
SELECT * FROM (
    SELECT
         ''			AS	CL_NAME
        ,0.00		AS	CL_VALUE
        ,NULL		AS	CL_PASSWORD
        ,'N'		AS	CL_CHECK
		,GETDATE()	AS	CL_DATE
        ,NULL		AS	CL_DUMMY
    WHERE 0 <> 0
    --					CL_NAME				CL_VALUE			CL_PASSWORD								CL_CHECK	CL_DATE											CL_DUMMY
    UNION ALL SELECT	'Alice Johnson'		,100.50				,HASHBYTES('MD5', 'password123')		,'N'		,CONVERT(DATETIME,'05/01/2023 14:23',103)		,NULL
    UNION ALL SELECT	'Bob Smith'			,200.75				,HASHBYTES('MD5', 'securepassword456')	,'Y'		,CONVERT(DATETIME,'23/08/2004 06:02',103)		,NULL
    UNION ALL SELECT	'Charlie Brown'		,150.00				,HASHBYTES('MD5', 'mypassword789')		,'N'		,CONVERT(DATETIME,'10/04/2015 17:48',103)		,NULL
    UNION ALL SELECT	'Diana Ross'		,175.30				,HASHBYTES('MD5', 'diana123')			,'Y'		,CONVERT(DATETIME,'02/07/2020 09:01',103)		,NULL
    UNION ALL SELECT	'Edward King'		,120.00				,HASHBYTES('MD5', 'kingpassword')		,'N'		,CONVERT(DATETIME,'14/05/2007 13:43',103)		,NULL
) AS AL_DATA
WHERE NOT EXISTS (
	SELECT TOP 1 NULL
	FROM TB_DUMMY
	WHERE TB_DUMMY.CL_NAME = AL_DATA.CL_NAME
	AND TB_DUMMY.CL_VALUE = AL_DATA.CL_VALUE
	AND TB_DUMMY.CL_PASSWORD = AL_DATA.CL_PASSWORD
	AND TB_DUMMY.CL_CHECK = AL_DATA.CL_CHECK
);
SELECT
	 TB_DUMMY.CL_ID
	AS CL_ID
    ,TB_DUMMY.CL_NAME
	AS CL_NAME
    ,TB_DUMMY.CL_VALUE
	AS CL_VALUE
    ,CONVERT(VARCHAR(32),TB_DUMMY.CL_PASSWORD,2)
	AS CL_PASSWORD
    ,TB_DUMMY.CL_CHECK
	AS CL_CHECK
	,CONVERT(VARCHAR(10),TB_DUMMY.CL_DATE,103) + ' ' + CONVERT(VARCHAR(5),TB_DUMMY.CL_DATE,114)
	AS CL_DATE
    ,TB_DUMMY.CL_DUMMY
	AS CL_DUMMY
FROM
	TB_DUMMY
GO
