-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires Santana
-- # - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.table : 0.0.1

-- # [ mssql ]
IF EXISTS (
	SELECT TOP 1 NULL
	FROM INFORMATION_SCHEMA.TABLES
	WHERE INFORMATION_SCHEMA.TABLES.TABLE_TYPE = 'BASE TABLE'
	AND INFORMATION_SCHEMA.TABLES.TABLE_NAME = 'TB_DUMMY'
)
DROP TABLE TB_DUMMY;
IF NOT EXISTS (
	SELECT TOP 1 NULL
	FROM INFORMATION_SCHEMA.TABLES
	WHERE INFORMATION_SCHEMA.TABLES.TABLE_TYPE = 'BASE TABLE'
	AND INFORMATION_SCHEMA.TABLES.TABLE_NAME = 'TB_DUMMY'
)
BEGIN
	CREATE TABLE TB_DUMMY (
		-- # : - column
		 CL_ID			INT	IDENTITY(1, 1)	NOT NULL
		,CL_DUMMY		INT						NULL
		,CL_NAME		VARCHAR		( 400)	NOT NULL
		,CL_VALUE		DECIMAL		(22,2)		NULL
		,CL_PASSWORD	BINARY		(  16)		NULL
		,CL_CHECK		VARCHAR		(   1)	NOT NULL
		,CL_DATE		DATETIME				NULL
			CONSTRAINT DF_TB_DUMMY_CL_CHECK
				DEFAULT('N')
			,CONSTRAINT CT_TB_DUMMY_CL_CHECK
				CHECK(CL_CHECK  IN ('Y','N'))

		-- # : - primary
		,CONSTRAINT PK_TB_DUMMY_CL_ID
		PRIMARY KEY (CL_ID)

		-- # : - foreign
		,CONSTRAINT FK_TB_DUMMY_CL_DUMMY
			FOREIGN KEY (CL_DUMMY)
			REFERENCES TB_DUMMY(CL_ID)
	)
END
