-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires Santana
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.python.mssql.backup.all.column. : 0.0.1

-- # [ mssql ]
SET NOCOUNT ON
DROP TABLE IF EXISTS #DATA
SELECT
	 CONVERT(VARCHAR(MAX),'')	AS [DATABASE]
	,CONVERT(VARCHAR(MAX),'')	AS [TABLE]
	,CONVERT(VARCHAR(MAX),'')	AS [COLUMN]
	,CONVERT(VARCHAR(MAX),'')	AS [TYPE]
	,CONVERT(VARCHAR(MAX),'')	AS [SIZE]
	,CONVERT(VARCHAR(MAX),'')	AS [NULL]
	,CONVERT(VARCHAR(MAX),'')	AS [DEFAULT]
	,CONVERT(INT,00)			AS [ORDER]
INTO #DATA
WHERE 0 <> 0
DECLARE @RUN VARCHAR(MAX) = ''
DECLARE @SCRIPT VARCHAR(MAX) = (''
	+ CHAR(13) + '		USE P_DATABASE'
	+ CHAR(13) + '		INSERT INTO #DATA'
	+ CHAR(13) + '		SELECT'
	+ CHAR(13) + '			 AL_TABLE.TABLE_CATALOG'
	+ CHAR(13) + '			AS [DATABASE]'
	+ CHAR(13) + '			,AL_TABLE.TABLE_NAME'
	+ CHAR(13) + '			AS [TABLE]'
	+ CHAR(13) + '			,AL_COLUMN.COLUMN_NAME'
	+ CHAR(13) + '			AS [COLUMN]'
	+ CHAR(13) + '			,UPPER(AL_COLUMN.DATA_TYPE)'
	+ CHAR(13) + '			AS [TYPE]'
	+ CHAR(13) + '			,(CASE'
	+ CHAR(13) + '				WHEN UPPER(AL_COLUMN.DATA_TYPE) IN ('''''
	+ CHAR(13) + '					,''DECIMAL'''
	+ CHAR(13) + '					,''NUMERIC'''
	+ CHAR(13) + '				)'
	+ CHAR(13) + '				THEN ''('' + CONVERT(VARCHAR,AL_COLUMN.NUMERIC_PRECISION) + '','' + CONVERT(VARCHAR,AL_COLUMN.NUMERIC_SCALE) + '')'''
	+ CHAR(13) + '				WHEN UPPER(AL_COLUMN.DATA_TYPE) IN ('''''
	+ CHAR(13) + '					,''BINARY'''
	+ CHAR(13) + '					,''CHAR'''
	+ CHAR(13) + '					,''NCHAR'''
	+ CHAR(13) + '					,''NVARCHAR'''
	+ CHAR(13) + '					,''VARBINARY'''
	+ CHAR(13) + '					,''VARCHAR'''
	+ CHAR(13) + '				)'
	+ CHAR(13) + '				THEN ''('' + REPLACE(CONVERT(VARCHAR,AL_COLUMN.CHARACTER_MAXIMUM_LENGTH),''-1'',''MAX'') + '')'''
	+ CHAR(13) + '				ELSE '''''
	+ CHAR(13) + '			END)'
	+ CHAR(13) + '			AS [SIZE]'
	+ CHAR(13) + '			,(CASE UPPER(AL_COLUMN.IS_NULLABLE)'
	+ CHAR(13) + '				WHEN ''YES'''
	+ CHAR(13) + '				THEN ''NULL'''
	+ CHAR(13) + '				ELSE ''NOT NULL'''
	+ CHAR(13) + '			END)'
	+ CHAR(13) + '			AS [NULL]'
	+ CHAR(13) + '			,ISNULL(''DEFAULT'' + '' '' + AL_COLUMN.COLUMN_DEFAULT,'''')'
	+ CHAR(13) + '			AS [DEFAULT]'
	+ CHAR(13) + '			,AL_COLUMN.ORDINAL_POSITION'
	+ CHAR(13) + '			AS [ORDER]'
	+ CHAR(13) + '		FROM'
	+ CHAR(13) + '			INFORMATION_SCHEMA.TABLES AL_TABLE WITH(NOLOCK)'
	+ CHAR(13) + '			INNER JOIN INFORMATION_SCHEMA.COLUMNS AS AL_COLUMN WITH(NOLOCK)'
	+ CHAR(13) + '				ON AL_COLUMN.TABLE_NAME = AL_TABLE.TABLE_NAME'
	+ CHAR(13) + '		WHERE 0 = 0'
	+ CHAR(13) + '			AND AL_TABLE.TABLE_TYPE = N''BASE TABLE'''
	+ CHAR(13) + '			AND AL_TABLE.TABLE_CATALOG = DB_NAME()'
	+ CHAR(13) + '			AND AL_TABLE.TABLE_SCHEMA = SCHEMA_NAME()'
)
DECLARE @NAME VARCHAR(64)
DECLARE CR_CURSOR CURSOR FOR SELECT [NAME]
FROM SYSDATABASES WITH(NOLOCK)
WHERE [NAME] NOT IN ('dbSQL2008','dw','master','tempdb','model','msdb','Northwind','Traces') ORDER BY [NAME]
OPEN CR_CURSOR
FETCH NEXT FROM CR_CURSOR INTO @NAME
WHILE (@@FETCH_STATUS = 0)
BEGIN
	SET @RUN = REPLACE(@SCRIPT,'P_DATABASE',@NAME)
	EXEC(@RUN)
	FETCH NEXT FROM CR_CURSOR INTO @NAME
END
CLOSE CR_CURSOR
DEALLOCATE CR_CURSOR
SELECT
	 [DATABASE]
	,[TABLE]
	,[COLUMN]
	,(
		REPLACE(
		REPLACE(
		REPLACE(
		REPLACE(
		REPLACE(
		REPLACE(
		REPLACE(
			(''
				+ CHAR(13) + 'IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.TABLES WITH(NOLOCK) WHERE TABLE_NAME = ''P_TABLE'')'
				+ CHAR(13) + 'CREATE TABLE [P_TABLE] ([P_COLUMN] [P_TYPE] P_SIZE P_NULL P_DEFAULT)'
				+ CHAR(13) + 'IF NOT EXISTS(SELECT TOP 1 NULL FROM INFORMATION_SCHEMA.COLUMNS WITH(NOLOCK) WHERE TABLE_NAME = ''P_TABLE'' AND COLUMN_NAME = ''P_COLUMN'')'
				+ CHAR(13) + 'ALTER TABLE [P_TABLE] ADD [P_COLUMN] [P_TYPE] P_SIZE P_NULL P_DEFAULT'
			)
			,'P_DATABASE'
			,[DATABASE]
		)
			,'P_TABLE'
			,[TABLE]
		)
			,'P_COLUMN'
			,[COLUMN]
		)
			,'P_TYPE'
			,[TYPE]
		)
			,'P_SIZE'
			,[SIZE]
		)
			,'P_NULL'
			,[NULL]
		)
			,'P_DEFAULT'
			,[DEFAULT]
		)
	)
	AS [SCRIPT]
FROM #DATA
ORDER BY
	 [DATABASE]		ASC
	,[TABLE]		ASC
	,[ORDER]		ASC
DROP TABLE IF EXISTS #DATA
