-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires Santana
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.list.object : 26.2.21.1

-- # [ mssql ]
SELECT
	 CL_NANE = NAME
	,CL_TYPE = (CASE XTYPE
		WHEN 'AF' THEN 'AGGREGATE FUNCTION (CLR)'
		WHEN 'C'  THEN 'CHECK CONSTRAINT'
		WHEN 'D'  THEN 'DEFAULT CONSTRAINT'
		WHEN 'F'  THEN 'FOREIGN KEY CONSTRAINT'
		WHEN 'FN' THEN 'SCALAR FUNCTION'
		WHEN 'FS' THEN 'CLR SCALAR FUNCTION'
		WHEN 'FT' THEN 'CLR TABLE-VALUED FUNCTION'
		WHEN 'IF' THEN 'INLINE TABLE-VALUED FUNCTION'
		WHEN 'IT' THEN 'INTERNAL TABLE'
		WHEN 'P'  THEN 'STORED PROCEDURE'
		WHEN 'PC' THEN 'CLR STORED PROCEDURE'
		WHEN 'PK' THEN 'PRIMARY KEY CONSTRAINT'
		WHEN 'R'  THEN 'RULE'
		WHEN 'RF' THEN 'REPLICATION FILTER PROCEDURE'
		WHEN 'S'  THEN 'SYSTEM TABLE'
		WHEN 'SN' THEN 'SYNONYM'
		WHEN 'SQ' THEN 'SERVICE QUEUE'
		WHEN 'TA' THEN 'CLR TRIGGER'
		WHEN 'TF' THEN 'TABLE-VALUED FUNCTION'
		WHEN 'TR' THEN 'SQL TRIGGER'
		WHEN 'TT' THEN 'TABLE TYPE'
		WHEN 'U'  THEN 'USER TABLE'
		WHEN 'UQ' THEN 'UNIQUE CONSTRAINT'
		WHEN 'V'  THEN 'VIEW'
		WHEN 'X'  THEN 'EXTENDED STORED PROCEDURE'
		ELSE 'UNKNOWN'
    END)
FROM
	SYSOBJECTS WITH(NOLOCK)
WHERE 0 = 0
ORDER BY
	CL_NANE
