-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires Santana
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.mssql.list.table : 26.2.21.1

-- # [ mssql ]
SELECT
	 CL_TABLE		= AL_TABLE.TABLE_NAME
	,CL_COLUMN		= AL_COLUMN.COLUMN_NAME
	,CL_TYPE		= UPPER(AL_COLUMN.DATA_TYPE)
	,CL_SIZE		= (CASE
		WHEN COLUMNPROPERTY(
				OBJECT_ID(AL_TABLE.TABLE_SCHEMA + '.' + AL_TABLE.TABLE_NAME),
				AL_COLUMN.COLUMN_NAME,
				'IsIdentity'
			 ) = 1
		THEN 
			'IDENTITY(' 
			+ CONVERT(VARCHAR, IDENT_SEED(AL_TABLE.TABLE_SCHEMA + '.' + AL_TABLE.TABLE_NAME))
			+ ',' 
			+ CONVERT(VARCHAR, IDENT_INCR(AL_TABLE.TABLE_SCHEMA + '.' + AL_TABLE.TABLE_NAME))
			+ ')'
		WHEN UPPER(AL_COLUMN.DATA_TYPE) IN (''
			,'BIGINT'
			,'BIT'
			,'DATE'
			,'DATETIME'
			,'FLOAT'
			,'IMAGE'
			,'INT'
			,'MONEY'
			,'NTEXT'
			,'SMALLDATETIME'
			,'SMALLINT'
			,'TEXT'
			,'TIME'
			,'TINYINT'
		)
		THEN ''
		WHEN UPPER(AL_COLUMN.DATA_TYPE) IN (''
			,'CHAR'
			,'NCHAR'
			,'NVARCHAR'
			,'VARBINARY'
			,'VARCHAR'
		)
		THEN (''
			+ REPLACE(CONVERT(VARCHAR,AL_COLUMN.CHARACTER_MAXIMUM_LENGTH),'-1','MAX')
		)
		WHEN UPPER(AL_COLUMN.DATA_TYPE) IN (''
			,'DECIMAL'
			,'NUMERIC'
		)
		THEN (''
			+ CONVERT(VARCHAR,AL_COLUMN.NUMERIC_PRECISION)
			+ ','
			+ CONVERT(VARCHAR,AL_COLUMN.NUMERIC_SCALE)
		)
		ELSE ''
	END)
	,CL_NULL		= (CASE
		WHEN UPPER(AL_COLUMN.IS_NULLABLE) = 'YES'
		THEN 'NULL'
		ELSE 'NOT NULL'
	END)
	,CL_DEFAULT		= ISNULL(AL_COLUMN.COLUMN_DEFAULT,'')
FROM
	INFORMATION_SCHEMA.TABLES AS AL_TABLE WITH(NOLOCK)
	INNER JOIN INFORMATION_SCHEMA.COLUMNS AS AL_COLUMN WITH(NOLOCK)
		ON AL_COLUMN.TABLE_NAME = AL_TABLE.TABLE_NAME
WHERE 0 = 0
	AND AL_TABLE.TABLE_TYPE = 'BASE TABLE'
	 /*
	AND AL_COLUMN.DATA_TYPE NOT IN (''
		,'BIGINT'
		,'BIT'
		,'CHAR'
		,'DATE'
		,'DATETIME'
		,'DECIMAL'
		,'FLOAT'
		,'IMAGE'
		,'INT'
		,'MONEY'
		,'NCHAR'
		,'NTEXT'
		,'NUMERIC'
		,'NVARCHAR'
		,'SMALLDATETIME'
		,'SMALLINT'
		,'TEXT'
		,'TIME'
		,'TINYINT'
		,'VARBINARY'
		,'VARCHAR'
	)
	-- */
ORDER BY
	 AL_TABLE.TABLE_NAME
	,AL_COLUMN.COLUMN_NAME
