-- # [ zrfisaac ]

-- # [ about ]
-- # - author : Isaac Caires
-- # . - email : zrfisaac@gmail.com
-- # . - site : zrfisaac.github.io
-- # - version : zrfisaac.postgres.list.table : 1.0.0

-- # [ postgres ]
SELECT
	 UPPER(AL_TABLE.TABLE_NAME)
	AS "TABLE"
	,UPPER(AL_COLUMN.COLUMN_NAME)
	AS "COLUMN"
	,AL_COLUMN.*
FROM
	INFORMATION_SCHEMA.TABLES AS AL_TABLE
	INNER JOIN INFORMATION_SCHEMA.COLUMNS AS AL_COLUMN
		ON UPPER(AL_COLUMN.TABLE_NAME) = UPPER(AL_TABLE.TABLE_NAME)
WHERE 0 = 0
	AND UPPER(AL_TABLE.TABLE_SCHEMA) = UPPER(CURRENT_SCHEMA)
	AND UPPER(AL_TABLE.TABLE_TYPE) = 'BASE TABLE'
	AND UPPER(AL_TABLE.TABLE_NAME) LIKE UPPER(CONCAT('%','','%'))
	AND UPPER(AL_COLUMN.COLUMN_NAME) LIKE UPPER(CONCAT('%','','%'))
ORDER BY
	 UPPER(AL_TABLE.TABLE_NAME)
	,AL_COLUMN.ORDINAL_POSITION
