#!/bin/bash
# [ zrfisaac ]

# [ about ]
# - author : Isaac Caires
# . - email : zrfisaac@gmail.com
# . - site : zrfisaac.github.io
# - version : zrfisaac.web.bash.folder : 0.0.1

# [ bash ]
_list=""
_list="${_list} default"
_list="${_list} default/desktop"
_list="${_list} default/dosbox"
_list="${_list} default/picture"
_list="${_list} default/template"
_list="${_list} default/video"
_list="${_list} default/virtualbox"
_list="${_list} default/vmware"
_list="${_list} binary"
_list="${_list} course"
_list="${_list} data"
_list="${_list} data/csv"
_list="${_list} data/database"
_list="${_list} data/mysql"
_list="${_list} data/mssql"
_list="${_list} data/oracle"
_list="${_list} data/postgres"
_list="${_list} data/sqlite"
_list="${_list} document"
_list="${_list} download"
_list="${_list} fork"
_list="${_list} game"
_list="${_list} manual"
_list="${_list} memory"
_list="${_list} music"
_list="${_list} product"
_list="${_list} profile"
_list="${_list} project"
_list="${_list} prototype"
_list="${_list} public"
_list="${_list} repository"
_list="${_list} repository/itch"
_list="${_list} repository/game"
_list="${_list} repository/os"
_list="${_list} repository/os/archlinux"
_list="${_list} repository/os/debian"
_list="${_list} repository/os/macos"
_list="${_list} repository/os/manjaro"
_list="${_list} repository/os/windows"
_list="${_list} repository/program"
_list="${_list} research"
_list="${_list} research/bash"
_list="${_list} research/batch"
_list="${_list} research/csharp"
_list="${_list} research/lazarus"
_list="${_list} research/lua"
_list="${_list} research/mvc"
_list="${_list} research/pascal"
_list="${_list} research/python"
_list="${_list} research/razor"
_list="${_list} resource"
_list="${_list} rom"
_list="${_list} source"
_list="${_list} stream"
_list="${_list} stream/anime"
_list="${_list} stream/cartoon"
_list="${_list} stream/movie"
_list="${_list} stream/tiktok"
_list="${_list} stream/video"
_list="${_list} stream/youtube"
_list="${_list} tool"
_list="${_list} trash"
_list="${_list} trash/00-any"
_list="${_list} wallpaper"
_list="${_list} web"
_list="${_list} web/apache"
_list="${_list} web/iis"
_list="${_list} web/tomcat"
_list="${_list} wine"
_list="${_list} windows"
_list="${_list} work"
for _folder in ${_list}; do [ ! -d "${_folder}" ] && mkdir -p "${_folder}"; done
